{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 1 square case billard\n"
   ]
  },
  {
   "cell_type": "code",
<<<<<<< HEAD:simulation_tkinter.ipynb
   "execution_count": 65,
=======
   "execution_count": 16,
>>>>>>> 54edcba04618f9b73e80a32614f57241f07f047d:rapport/simulation_tkinter.ipynb
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
<<<<<<< HEAD:simulation_tkinter.ipynb
     "text": [
      "Evaluatin angle \n",
      "240.0\n",
      "vhvhvhvvhvhvvhvh\n",
      "[240.0, 9, 7]\n"
     ]
=======
     "name": "stdout",
     "text": "Evaluatin angle\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nEvaluatin angle\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\nVH\n"
>>>>>>> 54edcba04618f9b73e80a32614f57241f07f047d:rapport/simulation_tkinter.ipynb
    }
   ],
   "source": [
    "from tkinter import* \n",
    "import math\n",
    "from random import randrange\n",
    "\n",
    "\n",
    "# initialisation of a basic window with minimize button ...\n",
    "\n",
    "angle = 0\n",
    "speed = 20\n",
    "WIDTH = 500\n",
    "HEIGHT = 500\n",
    "X1rec = WIDTH/2 - 20\n",
    "Y1rec = HEIGHT/2 - 20\n",
    "X2rec = X1rec + 20\n",
    "Y2rec = Y1rec + 20\n",
    "X1Line = 0\n",
    "Y1Line = 0\n",
    "X2Line = 0\n",
    "Y2Line = 0\n",
    "Name = str()\n",
    "test = \"v,h\"\n",
    "button = False\n",
    "## calculate the coorrdenate of the pool stick\n",
    "def calculateLinePosition():\n",
    "    global X1Line\n",
    "    X1Line = X1rec +(X2rec - X1rec)/2\n",
    "    global Y1Line\n",
    "    Y1Line = Y1rec +(Y2rec - Y1rec)/2\n",
    "    global X2Line\n",
    "    X2Line = X1Line + 100*math.sin(angle*math.pi/180)\n",
    "    global Y2Line\n",
    "    Y2Line = Y1Line + 100*math.cos(angle*math.pi/180)\n",
    "\n",
    "    \n",
    "calculateLinePosition()\n",
    "\n",
    "def evaluateimpact():\n",
    "    global Name \n",
    "   \n",
    "    \n",
    "    if  Y1rec - float(speed)*math.cos(angle*math.pi/180) > HEIGHT - 60:#when the ball hits the downside side \n",
    "        Name=Name+ test[2] \n",
    "    if  Y1rec - float(speed)*math.cos(angle*math.pi/180) <=0:#when the ball hits the upperside side\n",
    "        Name=Name+ test[2]\n",
    "     \n",
    "    if X1rec - float(speed)*math.sin(angle*math.pi/180) > WIDTH - 20:#when the ball hits the rightside side\n",
    "        Name=Name+ test[0]\n",
    "    if X1rec - float(speed)*math.sin(angle*math.pi/180) <=0:#when the ball hits the leftside side\n",
    "        Name=Name+ test[0]\n",
    "evaluateimpact()\n",
    "\n",
    "\n",
    "\n",
    "root = Tk()#creating and openning a window\n",
    "root.title(\"Billard Simulation\")\n",
    "root.geometry(\"800x600\")#size of the window \n",
    "#creatin a frame for the buttons in th bottom\n",
    "\n",
    "bottomFrame=Frame(root)\n",
    "bottomFrame.pack(side=BOTTOM)\n",
    "\n",
    "#giv a name to our window\n",
    "\n",
    "thelabel=Label(root,text=\"square case billard simulation\") \n",
    "thelabel.pack()\n",
    "\n",
    "#creating buttons (pause and restart buttons )\n",
    "def pause(event):#function of the button \n",
    "    global button\n",
    "    button = False\n",
    "    \n",
    "Pause=Button(bottomFrame,text=\"Pause\",fg=\"Blue\")\n",
    "Pause.bind(\" <Button-1>\",pause)\n",
    "Pause.pack(fill=X)\n",
    "def Start(event):#function of the button\n",
    "    global button\n",
    "    button = True\n",
    "restart=Button(bottomFrame,text=\"Start\",fg=\"Green\")\n",
    "restart.bind(\"<Button-1>\",Start)\n",
    "restart.pack(fill=X)\n",
    "\n",
    "#creating entries ( angle)\n",
    "\n",
    "label1=Label(root,text=\"please choose an angle to start with then press enter\")#title of the entry\n",
    "label1.pack()\n",
    "\n",
    "#obtaining data from our entry  \n",
    "\n",
    "def evaluateangle(event):\n",
    "    print(\"Evaluatin angle \" )\n",
    "    global angle\n",
    "    \n",
    "    \n",
    "    entry = entrySpace.get()\n",
    "    if entry :\n",
    "        angle = float(entry)\n",
    "        ans.configure(text=\"Your angle is \" +str(angle))\n",
    "        ans.pack()\n",
    "        calculateLinePosition()\n",
    "        canvas.delete('all')\n",
    "        canvas.create_rectangle(0, 0, WIDTH, HEIGHT,fill=\"Green\",outline='Brown')\n",
    "        canvas.create_oval(X1rec, Y1rec, X2rec, Y2rec , width = 0, fill = 'blue')\n",
    "        canvas.create_line(X1Line, Y1Line, X2Line, Y2Line, width= 2,fill = 'brown')\n",
    "        canvas.pack()\n",
    "    \n",
    "entrySpace=Entry(root)#creating an entry space    \n",
    "entrySpace.bind(\"<Return>\",evaluateangle)\n",
    "entrySpace.pack()\n",
    "ans=Label(root)\n",
    "ans.configure(text=\"Your initial angle is \" +  str(angle))\n",
    "ans.pack()\n",
    "\n",
    "\n",
    "canvas=Canvas(root,width=WIDTH,height=HEIGHT)\n",
    "canvas.pack()\n",
    "canvas.create_rectangle(0,0,WIDTH,HEIGHT,fill=\"Green\",outline=\"brown\")\n",
    "canvas.create_oval(X1rec, Y1rec, X2rec, Y2rec , width = 0, fill = 'blue')\n",
    "#canvas.create_line(X1Line, Y1Line, X2Line, Y2Line, width= 2,fill = 'brown')\n",
    "canvas.pack()\n",
    "def refresh():\n",
    "    if(button):\n",
    "        global X1rec\n",
    "        global X2rec\n",
    "        global Y1rec\n",
    "        global Y2rec\n",
    "        global speed\n",
    "        global angle\n",
    "        global HEIGHT\n",
    "        global WIDTH\n",
    "        global Name\n",
    "        global v \n",
    "        global h\n",
    "        if X1rec - float(speed)*math.sin(angle*math.pi/180) >= 0 :\n",
    "            if X1rec - float(speed)*math.sin(angle*math.pi/180) > WIDTH - 20:\n",
    "                if angle%360 >= 90 :\n",
    "                    angle = (360 - angle)%360\n",
    "                else :\n",
    "                    angle = (angle + 270)%360\n",
    "            X1rec = X1rec - float(speed)*math.sin(angle*math.pi/180)\n",
    "            X2rec = X1rec + 20\n",
    "               \n",
    "        else :\n",
    "            if angle%360 >= 90 :\n",
    "                angle = (360 - angle)%360\n",
    "            else :\n",
    "                angle = (angle + 270)%360\n",
    "            X1rec = X1rec - float(speed)*math.sin(angle*math.pi/180)\n",
    "            X2rec = X1rec + 20\n",
    "        if Y1rec - float(speed)*math.cos(angle*math.pi/180) >= 0:\n",
    "            if Y1rec - float(speed)*math.cos(angle*math.pi/180) > HEIGHT - 60:\n",
    "                if angle%360 <= 180 :\n",
    "                    angle = (360 + 180 - angle)%360\n",
    "                else :\n",
    "                    angle = (180 - angle)%360\n",
    "            Y1rec = Y1rec - float(speed)*math.cos(angle*math.pi/180)\n",
    "            Y2rec = Y1rec + 20\n",
    "        else :\n",
    "            if angle %360<= 90 :\n",
    "                angle = (180 - angle)%360\n",
    "            else :\n",
    "                angle = (angle + 270)%360\n",
    "            Y1rec = Y1rec - float(speed)*math.cos(angle*math.pi/180)\n",
    "            Y2rec = Y1rec + 20\n",
    "    \n",
    "        ans.configure(text=\"Your angle is \" +str(angle))\n",
    "        ans.pack()\n",
    "        calculateLinePosition()\n",
<<<<<<< HEAD:simulation_tkinter.ipynb
    "        #canvas.delete('all')\n",
    "        canvas.create_rectangle(0, 0, WIDTH, HEIGHT, fill=\"Green\",outline=\"brown\")\n",
    "        canvas.create_oval(X1rec, Y1rec, X2rec, Y2rec , width = 0, fill = 'blue')\n",
    "        #canvas.create_line(X1Line, Y1Line, X2Line, Y2Line, width= 2,fill = 'brown')\n",
=======
    "        def evaluatecolision():\n",
    "            name = \"VH\"\n",
    "            if Y1Line - (Y2rec-Y1rec)/2 ==0:\n",
    "                name += name[0]\n",
    "            if X1Line - (X2rec-X1rec)/2 ==0:\n",
    "                name += name[1]\n",
    "            print(name)\n",
    "        evaluatecolision()\n",
    "\n",
    "        canvas.delete('all')\n",
    "        canvas.create_rectangle(0, 0, WIDTH, HEIGHT, fill=\"Green\")\n",
    "        canvas.create_oval(X1rec, Y1rec, X2rec, Y2rec , width = 0, fill = 'white')\n",
    "        canvas.create_line(X1Line, Y1Line, X2Line, Y2Line, width= 2,fill = 'white')\n",
>>>>>>> 54edcba04618f9b73e80a32614f57241f07f047d:rapport/simulation_tkinter.ipynb
    "        canvas.pack()\n",
    "        \n",
    "    #canvas.after(1000,refresh)\n",
    "    canvas.after(100,refresh)\n",
    "    evaluateimpact()\n",
    "    ans.configure(text=\"The result name is\" +  str( Name))\n",
    "    ans.pack()\n",
    "canvas.after(1,refresh)\n",
    "root.mainloop()#to maintain the window open\n",
    "print(angle)\n",
    "if  len(Name)<2000:\n",
    "    print(Name)\n",
    "#if  len(Name)>20:\n",
    "## statistics  \n",
    "V=0 #number of the letter v in the name \n",
    "H=0 #number of the letter H in the name\n",
    "for i in range(len(Name)):\n",
    "    if Name[i]=='v':\n",
    "       V=V+1\n",
    "    else :\n",
    "        H=H+1\n",
    "data=[angle,V,H]\n",
    "print(data)\n",
    "#if len(Name)>10:\n",
    "    #break"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 120,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[210.0, 0, 3]"
      ]
     },
     "execution_count": 120,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 2flat torus case billard"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "torus represnetaion "
   ]
  },
  {
   "cell_type": "code",
<<<<<<< HEAD:simulation_tkinter.ipynb
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 749, in callit\n",
      "    func(*args)\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 338, in idle_draw\n",
      "    self.draw()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\backend_tkagg.py\", line 10, in draw\n",
      "    _backend_tk.blit(self._tkphoto, self.renderer._renderer, (0, 1, 2, 3))\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\site-packages\\matplotlib\\backends\\_backend_tk.py\", line 80, in blit\n",
      "    photoimage.blank()\n",
      "  File \"C:\\Users\\sarab\\Anaconda3\\lib\\tkinter\\__init__.py\", line 3548, in blank\n",
      "    self.tk.call(self.name, 'blank')\n",
      "_tkinter.TclError: invalid command name \"pyimage302\"\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "from tkinter import* \n",
    "import matplotlib\n",
    "matplotlib.use('TkAgg')\n",
    "\n",
    "from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg\n",
    "import matplotlib.pyplot as plt\n",
    "from mpl_toolkits.mplot3d import axes3d\n",
    " \n",
    "root = Tk()\n",
    " \n",
    "#fig = plt.figure()\n",
    "angle = np.linspace(0, 2 * np.pi, 32)\n",
    "theta, phi = np.meshgrid(angle, angle)\n",
    "r, R = 0.9, 1.\n",
    "X = (R + r * np.cos(phi)) * np.cos(theta)\n",
    "Y = (R + r * np.cos(phi)) * np.sin(theta)\n",
    "Z = r * np.sin(phi)\n",
    "# Display the mesh\n",
    "fig = plt.figure()\n",
    "ax = fig.gca(projection = '3d')\n",
    "ax.set_xlim3d(-1, 1)\n",
    "ax.set_ylim3d(-1, 1)\n",
    "ax.set_zlim3d(-1, 1)\n",
    "ax.plot_surface(X, Y, Z, color = 'g', rstride = 1, cstride = 1)\n",
    "plt.axis('off')\n",
    "plt.show()\n",
    "#plt.draw()\n",
    "canvas = FigureCanvasTkAgg(fig, master=root)\n",
    "plot_widget = canvas.get_tk_widget()\n",
    "plot_widget.grid(row=0, column=0)\n",
    "#tk.Button(root,text=\"Update\",command=update).grid(row=1, column=0)\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "What is a flat torus? It is a square whose sides correspond two by two. This means that to be imaginary living in this square, each time it is sorted by the upper side it is immediately reappeared by the lower side, the same for the right and left sides.\n"
=======
   "execution_count": 9,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "#create a Flat Torus\n",
    "import numpy as np\n",
    "import matplotlib as plt\n",
    "\n",
    "n = 100"
>>>>>>> 54edcba04618f9b73e80a32614f57241f07f047d:rapport/simulation_tkinter.ipynb
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.3-final"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}